# Generated by Django 2.0 on 2018-01-18 21:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180118_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 21, 48, 41, 917027, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 21, 48, 41, 916955, tzinfo=utc)),
        ),
    ]
