# Generated by Django 2.0.2 on 2018-02-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180204_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='color',
            field=models.CharField(default='#191919', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#191919', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='#191919', max_length=200),
        ),
    ]
