# Generated by Django 2.0.2 on 2018-02-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180205_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_completion_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
