# Generated by Django 2.0.2 on 2018-02-18 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_featurecomment_taskcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
