# Generated by Django 2.0.2 on 2018-02-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20180218_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='clock_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='clock_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
