# Generated by Django 2.0.2 on 2018-02-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20180219_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='in_work',
            field=models.BooleanField(default=False),
        ),
    ]
