# Generated by Django 2.0.2 on 2018-03-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20180228_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tz',
            field=models.CharField(default='(US/Eastern)', max_length=200),
        ),
    ]
