# Generated by Django 2.0 on 2018-01-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180113_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(default='', max_length=200),
        ),
    ]
