# Generated by Django 2.0 on 2018-01-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180113_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='upload_pics/profile-placeholder.png', null=True, upload_to='upload_pics/'),
        ),
    ]
