# Generated by Django 2.0 on 2018-01-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180115_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default='Company Name', max_length=200),
        ),
    ]
